package se.parze.sdbq;

import org.springframework.jdbc.core.JdbcTemplate;

import java.util.Map;

public class DatabaseTypeHSql implements DatabaseType {

    @Override
    public boolean dataSourceBelongToType(JdbcTemplate jdbcTemplate) {
        try {
            Map<String, Object> result = jdbcTemplate.queryForMap("Select Top 1 * From INFORMATION_SCHEMA.SYSTEM_TABLES");
            return result != null && result.containsKey("HSQLDB_TYPE");
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public String getCreateQueueTableSql(String queueTableName) {
        return "Create Table If Not Exists "+queueTableName+"("+
                "id Bigint Generated By Default As Identity, "+
                "item_id Bigint Not NULL, "+
                "started_at Timestamp, "+
                "prio Integer"+
                ")";
    }

    @Override
    public String getSqlSelectForUpdate(String queueTableName) {
        return "Select id From "+queueTableName+" "+
                "Where started_at is NULL "+
                "Order By id "+
                "Fetch First 1 Rows Only "+
                "For Update";
    }

}
